<?php
return array (
  'autogenerated-1-c4ca4238a0b923820dcc509a6f75849b' => 
  array (
    'base' => 'http://localhost:8080/schommer/autogenerated-1',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 1,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-10-d3d9446802a44259755d38e6d163e820' => 
  array (
    'base' => 'http://localhost:8080/schommer/autogenerated-10',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 10,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-13-c51ce410c124a10e0db5e4b97fc2af39' => 
  array (
    'base' => 'http://localhost:8080/schommer/autogenerated-13',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 13,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-15-9bf31c7ff062936a96d3c8bd1f8f2ff3' => 
  array (
    'base' => 'http://localhost:8080/schommer/autogenerated-15',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 15,
    'routes' => 
    array (
    ),
  ),
  'autogenerated-6-1679091c5a880faf6fb5e6087eb1b2dc' => 
  array (
    'base' => 'http://localhost:8080/schommer/autogenerated-6',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 6,
    'routes' => 
    array (
    ),
  ),
);
#